PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;

CREATE TABLE IF NOT EXISTS pipeline_runs (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	started_at_epoch_seconds INTEGER NOT NULL,
	completed_at_epoch_seconds INTEGER,
	matched_row_count INTEGER,
	enriched_row_count INTEGER,
	final_model_count INTEGER
);

CREATE TABLE IF NOT EXISTS aa_raw_models (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	fetched_at_epoch_seconds INTEGER,
	url TEXT NOT NULL,
	model_id TEXT,
	name TEXT,
	short_name TEXT,
	creator_name TEXT,
	model_url TEXT,
	release_date TEXT,
	deprecated INTEGER,
	reasoning_model INTEGER,
	open_weights INTEGER,
	commercial_allowed INTEGER,
	input_modality_text INTEGER,
	input_modality_image INTEGER,
	input_modality_video INTEGER,
	input_modality_speech INTEGER,
	output_modality_text INTEGER,
	output_modality_image INTEGER,
	output_modality_video INTEGER,
	output_modality_speech INTEGER,
	median_output_tokens_per_second REAL,
	median_time_to_first_token_seconds REAL,
	intelligence_index REAL,
	agentic_index REAL,
	coding_index REAL,
	omniscience_index REAL,
	omniscience_accuracy REAL,
	omniscience_nonhallucination_rate REAL,
	apex_agents REAL,
	critpt REAL,
	gdpval_normalized REAL,
	gpqa REAL,
	hle REAL,
	ifbench REAL,
	lcr REAL,
	mmmu_pro REAL,
	scicode REAL,
	terminalbench_hard REAL,
	input_cost REAL,
	reasoning_cost REAL,
	output_cost REAL,
	total_cost REAL,
	input_tokens REAL,
	reasoning_tokens REAL,
	answer_tokens REAL,
	output_tokens REAL,
	total_tokens REAL,
	logo_url TEXT,
	PRIMARY KEY (run_id, row_index)
);

CREATE TABLE IF NOT EXISTS models_dev_raw_models (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	fetched_at_epoch_seconds INTEGER,
	status_code INTEGER,
	url TEXT NOT NULL,
	provider_id TEXT NOT NULL,
	provider_name TEXT,
	provider_api TEXT,
	model_id TEXT NOT NULL,
	name TEXT,
	family TEXT,
	release_date TEXT,
	last_updated TEXT,
	open_weights INTEGER,
	reasoning INTEGER,
	tool_call INTEGER,
	cost_input REAL,
	cost_output REAL,
	cost_cache_read REAL,
	cost_cache_write REAL,
	cost_output_audio REAL,
	limit_context INTEGER,
	limit_output INTEGER,
	input_modality_text INTEGER,
	input_modality_image INTEGER,
	input_modality_audio INTEGER,
	input_modality_video INTEGER,
	input_modality_pdf INTEGER,
	output_modality_text INTEGER,
	output_modality_image INTEGER,
	output_modality_audio INTEGER,
	output_modality_video INTEGER,
	PRIMARY KEY (run_id, row_index)
);

CREATE TABLE IF NOT EXISTS deep_swe_raw_rows (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	fetched_at_epoch_seconds INTEGER,
	url TEXT NOT NULL,
	model TEXT NOT NULL,
	reasoning_effort TEXT,
	config TEXT,
	pass_at_1 REAL NOT NULL,
	ci_lo REAL,
	ci_hi REAL,
	ci_half REAL,
	mean_cost_usd REAL NOT NULL,
	mean_duration_seconds REAL NOT NULL,
	mean_output_tokens REAL NOT NULL,
	is_best_model_score INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (run_id, row_index)
);

CREATE TABLE IF NOT EXISTS terminal_bench_raw_rows (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	fetched_at_epoch_seconds INTEGER,
	url TEXT NOT NULL,
	agent TEXT,
	model TEXT NOT NULL,
	accuracy REAL,
	median_accuracy REAL,
	mean_accuracy REAL,
	frequency INTEGER,
	row_kind TEXT NOT NULL,
	PRIMARY KEY (run_id, row_index)
);

CREATE TABLE IF NOT EXISTS agents_last_exam_raw_rows (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	fetched_at_epoch_seconds INTEGER,
	url TEXT NOT NULL,
	split TEXT NOT NULL,
	harness TEXT,
	model TEXT NOT NULL,
	harness_variant TEXT,
	runs INTEGER,
	tasks INTEGER,
	split_tasks INTEGER,
	passes INTEGER,
	accuracy REAL,
	score REAL,
	total_duration_seconds REAL,
	total_input_tokens REAL,
	total_output_tokens REAL,
	median_accuracy REAL,
	mean_accuracy REAL,
	median_score REAL,
	mean_score REAL,
	median_total_duration_seconds REAL,
	mean_total_duration_seconds REAL,
	median_total_input_tokens REAL,
	mean_total_input_tokens REAL,
	median_total_output_tokens REAL,
	mean_total_output_tokens REAL,
	frequency INTEGER,
	row_kind TEXT NOT NULL,
	PRIMARY KEY (run_id, row_index)
);

CREATE TABLE IF NOT EXISTS openrouter_raw_rows (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	fetched_at_epoch_seconds INTEGER,
	url TEXT NOT NULL,
	row_kind TEXT NOT NULL,
	model_id TEXT,
	slug TEXT,
	permaslug TEXT,
	candidate_index INTEGER,
	selected_permaslug TEXT,
	metric TEXT,
	x TEXT,
	series TEXT,
	value REAL,
	throughput_tokens_per_second_median REAL,
	latency_seconds_median REAL,
	e2e_latency_seconds_median REAL,
	weighted_input_price_per_1m REAL,
	weighted_output_price_per_1m REAL,
	PRIMARY KEY (run_id, row_index)
);

CREATE TABLE IF NOT EXISTS processed_models (
	run_id INTEGER NOT NULL,
	stage TEXT NOT NULL,
	row_index INTEGER NOT NULL,
	model_id TEXT,
	provider_id TEXT,
	openrouter_id TEXT,
	name TEXT,
	aa_id TEXT,
	family TEXT,
	logo TEXT,
	attachment INTEGER,
	reasoning INTEGER,
	release_date TEXT,
	open_weights INTEGER,
	context INTEGER,
	context_input INTEGER,
	context_output INTEGER,
	input_modality_text INTEGER,
	input_modality_image INTEGER,
	input_modality_audio INTEGER,
	input_modality_video INTEGER,
	throughput_tokens_per_second_median REAL,
	latency_seconds_median REAL,
	e2e_latency_seconds_median REAL,
	cost_input REAL,
	cost_output REAL,
	cost_cache_read REAL,
	cost_cache_write REAL,
	cost_weighted_input REAL,
	cost_weighted_output REAL,
	cost_blended_price REAL,
	context_over_200k_input REAL,
	context_over_200k_output REAL,
	context_over_200k_cache_read REAL,
	context_over_200k_cache_write REAL,
	intelligence_index REAL,
	agentic_index REAL,
	coding_index REAL,
	omniscience_index REAL,
	omniscience_accuracy REAL,
	omniscience_nonhallucination_rate REAL,
	apex_agents REAL,
	critpt REAL,
	gdpval_normalized REAL,
	gpqa REAL,
	hle REAL,
	ifbench REAL,
	lcr REAL,
	mmmu_pro REAL,
	scicode REAL,
	terminalbench_hard REAL,
	deep_swe REAL,
	terminal_bench_2 REAL,
	agents_last_exam REAL,
	aa_task_cost REAL,
	aa_task_seconds REAL,
	aa_task_output_tokens REAL,
	deep_swe_task_cost REAL,
	deep_swe_task_seconds REAL,
	deep_swe_task_output_tokens REAL,
	agents_last_exam_task_cost REAL,
	agents_last_exam_task_seconds REAL,
	agents_last_exam_task_input_tokens REAL,
	agents_last_exam_task_output_tokens REAL,
	raw_intelligence_score REAL,
	raw_agentic_score REAL,
	raw_speed_score REAL,
	raw_value_score REAL,
	relative_intelligence_score REAL,
	relative_agentic_score REAL,
	relative_speed_score REAL,
	relative_value_score REAL,
	relative_overall_score REAL,
	PRIMARY KEY (run_id, stage, row_index)
);

CREATE TABLE IF NOT EXISTS debug (
	run_id INTEGER NOT NULL,
	row_index INTEGER NOT NULL,
	trace_kind TEXT NOT NULL,
	aa_id TEXT,
	aa_slug TEXT,
	aa_name TEXT,
	aa_raw_row_index INTEGER,
	candidate_rank INTEGER,
	candidate_model_id TEXT,
	candidate_provider_id TEXT,
	candidate_provider_name TEXT,
	candidate_name TEXT,
	candidate_score REAL,
	selected INTEGER,
	rejected INTEGER,
	rejection_reason TEXT,
	selected_model_id TEXT,
	models_dev_row_index INTEGER,
	openrouter_model_id TEXT,
	openrouter_model_stats_row_index INTEGER,
	PRIMARY KEY (run_id, row_index)
);

CREATE INDEX IF NOT EXISTS idx_aa_raw_models_model_id ON aa_raw_models(model_id);
CREATE INDEX IF NOT EXISTS idx_models_dev_raw_models_model_id ON models_dev_raw_models(model_id);
CREATE INDEX IF NOT EXISTS idx_openrouter_raw_rows_model_id ON openrouter_raw_rows(model_id);
CREATE INDEX IF NOT EXISTS idx_processed_models_model_id ON processed_models(model_id);
CREATE INDEX IF NOT EXISTS idx_debug_aa_id ON debug(aa_id);
CREATE INDEX IF NOT EXISTS idx_debug_candidate_model_id ON debug(candidate_model_id);
CREATE INDEX IF NOT EXISTS idx_debug_selected_model_id ON debug(selected_model_id);
