/** Provider icon generation for Model Atlas. */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import {
	resizeLogoToPng,
	statsLogoCacheDir,
} from "../src/model-atlas/logo-cache";
import { providerIconColor } from "../src/model-atlas/logo-color";

type ProviderAsset = {
	logo: string;
	color: string;
};

type ProviderAssetMap = Record<string, ProviderAsset>;

type SnapshotModel = {
	provider?: string | null;
	logo?: string | null;
};

const SNAPSHOT_PATH = "public/model-atlas-snapshot.json";
const GENERATED_PATH = "app/dashboard/shared/providerAssets.generated.ts";
const LOGO_SIZE = 64;

const force = process.argv.includes("--force");

const existingAssets = force ? {} : await readExistingAssets();
const providerSources = await readProviderSources();
const nextAssets: ProviderAssetMap = { ...existingAssets };

for (const [provider, source] of [...providerSources].sort()) {
	if (nextAssets[provider] != null) {
		continue;
	}
	const sourceBuffer = await logoSourceBuffer(provider, source);
	if (sourceBuffer == null) {
		continue;
	}
	const normalizedLogo = await resizeLogoToPng(sourceBuffer);
	const color = (await providerIconColor(normalizedLogo)) ?? "#eeeeea";
	nextAssets[provider] = {
		logo: svgDataUrl(normalizedLogo),
		color,
	};
}

await writeFile(resolve(GENERATED_PATH), providerAssetsModule(nextAssets));

console.log(
	JSON.stringify(
		{
			path: GENERATED_PATH,
			providers: Object.keys(nextAssets).length,
			added:
				Object.keys(nextAssets).length - Object.keys(existingAssets).length,
			force,
		},
		null,
		2,
	),
);

async function readExistingAssets(): Promise<ProviderAssetMap> {
	try {
		const moduleUrl = pathToFileURL(resolve(GENERATED_PATH)).href;
		const module = (await import(moduleUrl)) as {
			providerAssets?: ProviderAssetMap;
		};
		return module.providerAssets ?? {};
	} catch {
		return {};
	}
}

async function readProviderSources() {
	const snapshot = JSON.parse(await readFile(SNAPSHOT_PATH, "utf8")) as {
		models?: SnapshotModel[];
	};
	const providers = new Map<string, string>();
	for (const model of snapshot.models ?? []) {
		const provider = providerSlug(model.provider);
		if (provider.length === 0) {
			continue;
		}
		const logo = typeof model.logo === "string" ? model.logo : "";
		if (!providers.has(provider) || (providers.get(provider) === "" && logo)) {
			providers.set(provider, logo);
		}
	}
	return providers;
}

async function logoSourceBuffer(provider: string, source: string) {
	if (source.startsWith("data:image/")) {
		return dataUrlBuffer(source);
	}
	try {
		return await readFile(resolve(statsLogoCacheDir(), `${provider}.png`));
	} catch {
		return null;
	}
}

function dataUrlBuffer(source: string) {
	const base64Marker = ";base64,";
	const base64Index = source.indexOf(base64Marker);
	if (base64Index >= 0) {
		return Buffer.from(
			source.slice(base64Index + base64Marker.length),
			"base64",
		);
	}
	const commaIndex = source.indexOf(",");
	if (commaIndex < 0) {
		return null;
	}
	return Buffer.from(decodeURIComponent(source.slice(commaIndex + 1)), "utf8");
}

function svgDataUrl(imageBuffer: Buffer) {
	const imageHref = `data:image/png;base64,${imageBuffer.toString("base64")}`;
	const svg = [
		`<svg xmlns="http://www.w3.org/2000/svg" width="${LOGO_SIZE}" height="${LOGO_SIZE}" viewBox="0 0 ${LOGO_SIZE} ${LOGO_SIZE}">`,
		`<image href="${imageHref}" width="${LOGO_SIZE}" height="${LOGO_SIZE}"/>`,
		"</svg>",
	].join("");
	return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}

function providerAssetsModule(assets: ProviderAssetMap) {
	const entries = Object.entries(assets)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([provider, asset]) =>
			[
				`\t${propertyKey(provider)}: {`,
				`\t\tcolor: ${JSON.stringify(asset.color)},`,
				`\t\tlogo: ${JSON.stringify(asset.logo)},`,
				"\t},",
			].join("\n"),
		)
		.join("\n");
	return [
		"// Generated by scripts/generate-provider-icons.ts. Do not edit directly.",
		"",
		"export type ProviderAsset = {",
		"\tcolor: string;",
		"\tlogo: string;",
		"};",
		"",
		"export const providerAssets = {",
		entries,
		"} as const satisfies Record<string, ProviderAsset>;",
		"",
	].join("\n");
}

function propertyKey(value: string) {
	return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value);
}

function providerSlug(provider: string | null | undefined) {
	return String(provider ?? "")
		.trim()
		.toLowerCase()
		.replace(/[^a-z0-9._-]+/g, "-")
		.replace(/^-+|-+$/g, "");
}
